version: "3"

services:
  app:
    image: node:12.4.0
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    dns:
        - 8.8.8.8
    network_mode: "bridge"
    command: bash -c "npm install && npm start"